/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author Alejo
 */
public class IncidenteSeguridad extends javax.swing.JPanel {

    /**
     * Creates new form IncidenteSeguridad
     */
    public IncidenteSeguridad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Seguridad = new javax.swing.JPanel();
        SelectorIncidente = new javax.swing.JComboBox<>();
        Incidente = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        Fecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        NivelDeRiesgo = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        Lugar = new javax.swing.JLabel();
        NivelBajo = new javax.swing.JRadioButton();
        NivelMedio = new javax.swing.JRadioButton();
        NivelAlto = new javax.swing.JRadioButton();
        Descripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        btnGuardaryenviar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Seguridad.setBackground(new java.awt.Color(0, 34, 64));
        Seguridad.setPreferredSize(new java.awt.Dimension(532, 452));

        SelectorIncidente.setBackground(new java.awt.Color(0, 0, 204));
        SelectorIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectorIncidente.setForeground(new java.awt.Color(255, 255, 255));
        SelectorIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Robo bienes", "Incendio instalaciones", "Vandalismo propiedad", "Intrusión no autorizada", "Sabotaje interno", "Sabotaje externo", "Inundación daños", "Terremoto estructural", "Corte energía", "Violencia laboral", "otros" }));

        Incidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Incidente.setForeground(new java.awt.Color(51, 255, 204));
        Incidente.setText("Incidente:");

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(51, 255, 204));
        Hora.setText("Hora:");

        txtHora.setBackground(new java.awt.Color(204, 255, 255));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 255, 204));
        Fecha.setText("Fecha:");

        txtFecha.setBackground(new java.awt.Color(204, 255, 255));

        NivelDeRiesgo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NivelDeRiesgo.setForeground(new java.awt.Color(51, 255, 204));
        NivelDeRiesgo.setText("Nivel de riesgo:");

        txtLugar.setBackground(new java.awt.Color(204, 255, 255));
        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });

        Lugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lugar.setForeground(new java.awt.Color(51, 255, 204));
        Lugar.setText("Lugar:");

        NivelBajo.setBackground(new java.awt.Color(0, 51, 255));
        NivelBajo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NivelBajo.setForeground(new java.awt.Color(255, 255, 255));
        NivelBajo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 102), new java.awt.Color(255, 255, 204), null, null));
        NivelBajo.setLabel("Bajo");

        NivelMedio.setBackground(new java.awt.Color(0, 51, 255));
        NivelMedio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NivelMedio.setForeground(new java.awt.Color(255, 255, 255));
        NivelMedio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 102), new java.awt.Color(255, 255, 204), null, null));
        NivelMedio.setLabel("Medio");

        NivelAlto.setBackground(new java.awt.Color(0, 51, 255));
        NivelAlto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NivelAlto.setForeground(new java.awt.Color(255, 255, 255));
        NivelAlto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 102), new java.awt.Color(255, 255, 204), null, null));
        NivelAlto.setLabel("Alto");

        Descripcion.setBackground(new java.awt.Color(51, 255, 204));
        Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(51, 255, 204));
        Descripcion.setText("Descripción:");

        txtDescripcion.setBackground(new java.awt.Color(204, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        btnRegresar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGuardaryenviar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardaryenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardaryenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardaryenviar.setText("Guardar y enviar");

        btnInicio.setBackground(new java.awt.Color(0, 0, 204));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ir a al inicio");
        btnInicio.setAutoscrolls(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeguridadLayout = new javax.swing.GroupLayout(Seguridad);
        Seguridad.setLayout(SeguridadLayout);
        SeguridadLayout.setHorizontalGroup(
            SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio)
                .addGap(83, 83, 83))
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addComponent(btnGuardaryenviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hora)
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Incidente)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeguridadLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lugar)
                            .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelDeRiesgo)
                            .addComponent(NivelBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NivelMedio)
                            .addComponent(NivelAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeguridadLayout.createSequentialGroup()
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Descripcion)
                            .addComponent(Fecha))
                        .addGap(298, 298, 298))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeguridadLayout.createSequentialGroup()
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(29, 29, 29))))
        );
        SeguridadLayout.setVerticalGroup(
            SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Incidente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(Lugar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NivelDeRiesgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NivelBajo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NivelMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NivelAlto))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, SeguridadLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(btnGuardaryenviar)
                .addGap(18, 18, 18)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnInicio))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      /*  ReporteIncidentePanel p4= new ReporteIncidentePanel();
        p4.setSize(830, 530);
        p4.setLocation(0,0);
        Seguridad.removeAll();
        Seguridad.add(p4);
        Seguridad.revalidate();
        Seguridad.repaint();*/
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
       /* VistaLogin p3= new VistaLogin ();
        p3.setSize(830, 530);
        p3.setLocation(0,0);
        Seguridad.removeAll();
        Seguridad.add(p3);
        Seguridad.revalidate();
        Seguridad.repaint();*/
    }//GEN-LAST:event_btnInicioActionPerformed

        public void addbtnRegresar(ActionListener listener){
            btnRegresar.addActionListener(listener);
    }
        public void addbtnInicio(ActionListener listener){
            btnInicio.addActionListener(listener);
        }        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Incidente;
    private javax.swing.JLabel Lugar;
    private javax.swing.JRadioButton NivelAlto;
    private javax.swing.JRadioButton NivelBajo;
    private javax.swing.JLabel NivelDeRiesgo;
    private javax.swing.JRadioButton NivelMedio;
    private javax.swing.JPanel Seguridad;
    private javax.swing.JComboBox<String> SelectorIncidente;
    private javax.swing.JButton btnGuardaryenviar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtLugar;
    // End of variables declaration//GEN-END:variables
}
