/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author Alejo
 */
public class IncidenteInstalacion extends javax.swing.JPanel {

    /**
     * Creates new form IncidenteInstalacion
     */
    public IncidenteInstalacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Instalacion = new javax.swing.JPanel();
        SelectorIncidente = new javax.swing.JComboBox<>();
        Incidente = new javax.swing.JLabel();
        Edificio = new javax.swing.JLabel();
        txtEdificio = new javax.swing.JTextField();
        Piso = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        Hora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        Fecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        Descripcion = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        btnGuardaryenviar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 255, 204));
        jLabel39.setText("Hora:");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 255, 204));
        jLabel41.setText("Fecha:");

        Instalacion.setBackground(new java.awt.Color(0, 34, 64));
        Instalacion.setPreferredSize(new java.awt.Dimension(532, 452));

        SelectorIncidente.setBackground(new java.awt.Color(0, 0, 204));
        SelectorIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectorIncidente.setForeground(new java.awt.Color(255, 255, 255));
        SelectorIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corte energía", "Fuga agua", "Caída objetos", "Derrumbe estructura", "Cable expuesto", "Piso resbaladizo", "Puerta bloqueada", "Iluminación insuficiente", "Equipos dañados", "Señalización ausente", "otros" }));

        Incidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Incidente.setForeground(new java.awt.Color(51, 255, 204));
        Incidente.setText("Incidente:");

        Edificio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Edificio.setForeground(new java.awt.Color(51, 255, 204));
        Edificio.setText("Edificio:");

        txtEdificio.setBackground(new java.awt.Color(204, 255, 255));

        Piso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Piso.setForeground(new java.awt.Color(51, 255, 204));
        Piso.setText("Piso:");

        Numero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Numero.setForeground(new java.awt.Color(51, 255, 204));
        Numero.setText("Número:");

        txtPiso.setBackground(new java.awt.Color(204, 255, 255));
        txtPiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPisoActionPerformed(evt);
            }
        });

        txtNumero.setBackground(new java.awt.Color(204, 255, 255));
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(51, 255, 204));
        Hora.setText("Hora:");

        txtHora.setBackground(new java.awt.Color(204, 255, 255));

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 255, 204));
        Fecha.setText("Fecha:");

        txtFecha.setBackground(new java.awt.Color(204, 255, 255));

        Descripcion.setBackground(new java.awt.Color(51, 255, 204));
        Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(51, 255, 204));
        Descripcion.setText("Descripción:");

        txtDescripcion.setBackground(new java.awt.Color(204, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane5.setViewportView(txtDescripcion);

        btnRegresar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGuardaryenviar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardaryenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardaryenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardaryenviar.setText("Guardar y enviar");

        btnInicio.setBackground(new java.awt.Color(0, 0, 204));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ir a al inicio");
        btnInicio.setAutoscrolls(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InstalacionLayout = new javax.swing.GroupLayout(Instalacion);
        Instalacion.setLayout(InstalacionLayout);
        InstalacionLayout.setHorizontalGroup(
            InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio)
                .addGap(68, 68, 68))
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addComponent(Incidente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Edificio)
                            .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Piso)
                                .addComponent(Numero)
                                .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(txtPiso)
                                .addComponent(txtEdificio))
                            .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Fecha)
                                .addComponent(txtFecha)
                                .addComponent(Descripcion)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                                .addComponent(txtHora))
                            .addComponent(Hora))
                        .addGap(26, 26, 26))))
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(btnGuardaryenviar)
                .addContainerGap(359, Short.MAX_VALUE))
        );
        InstalacionLayout.setVerticalGroup(
            InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Incidente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edificio)
                    .addComponent(Hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Piso)
                    .addComponent(Fecha))
                .addGap(5, 5, 5)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnGuardaryenviar)
                        .addGap(86, 86, 86))
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInicio)
                            .addComponent(btnRegresar))
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Instalacion, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Instalacion, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPisoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
      /*  ReporteIncidentePanel p4= new ReporteIncidentePanel();
        p4.setSize(830, 530);
        p4.setLocation(0,0);
        Instalacion.removeAll();
        Instalacion.add(p4);
        Instalacion.revalidate();
        Instalacion.repaint();*/
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
      /*  VistaLogin p3= new VistaLogin ();
        p3.setSize(830, 530);
        p3.setLocation(0,0);
        Instalacion.removeAll();
        Instalacion.add(p3);
        Instalacion.revalidate();
        Instalacion.repaint();*/
    }//GEN-LAST:event_btnInicioActionPerformed

        public void addbtnRegresar(ActionListener listener){
            btnRegresar.addActionListener(listener);
    }
        public void addbtnInicio(ActionListener listener){
            btnInicio.addActionListener(listener);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Edificio;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Incidente;
    private javax.swing.JPanel Instalacion;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Piso;
    private javax.swing.JComboBox<String> SelectorIncidente;
    private javax.swing.JButton btnGuardaryenviar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEdificio;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables
}
