/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import utils.ValidadorCamposIncidente;

/**
 *
 * @author Alejo
 */
public class VistaIncidenteTecnico extends javax.swing.JPanel {

    SpinnerDateModel horaModel;
    SpinnerDateModel fechaModel;
    private List errores;
    
    /**
     * Creates new form IncidenteTecnico
     */
    public VistaIncidenteTecnico() {
        initComponents();
       errores = new ArrayList<>();
       horaModel = new SpinnerDateModel();
       spinnerHora.setModel(horaModel);

        fechaModel = new SpinnerDateModel();
       
        spinnerFecha.setModel(fechaModel);
        
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerHora, "HH:mm a");
        spinnerHora.setEditor(editor);
        
        JSpinner.DateEditor editorFecha = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(editorFecha);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        Tecnico = new javax.swing.JPanel();
        Incidente = new javax.swing.JLabel();
        SelectorIncidente = new javax.swing.JComboBox<>();
        Marca = new javax.swing.JLabel();
        txtDispositivoAfectado = new javax.swing.JTextField();
        DispositivoAfectado = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        NumeroDeSerie = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        Modelo = new javax.swing.JLabel();
        txtNumeroDeSerie = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Ubicacion = new javax.swing.JLabel();
        txtUbicacion = new javax.swing.JTextField();
        Descripción = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnInicio = new javax.swing.JButton();
        btnGuardaryenviar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        Hora = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        spinnerHora = new javax.swing.JSpinner();
        spinnerFecha = new javax.swing.JSpinner();

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dispositivo Afectado:");

        jTextField7.setBackground(new java.awt.Color(204, 255, 255));

        jButton4.setBackground(new java.awt.Color(0, 153, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Recuperar Contraseña");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        Tecnico.setBackground(new java.awt.Color(0, 34, 64));
        Tecnico.setAutoscrolls(true);
        Tecnico.setPreferredSize(new java.awt.Dimension(532, 452));

        Incidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Incidente.setForeground(new java.awt.Color(51, 255, 204));
        Incidente.setText("Incidente:");

        SelectorIncidente.setBackground(new java.awt.Color(0, 0, 204));
        SelectorIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectorIncidente.setForeground(new java.awt.Color(255, 255, 255));
        SelectorIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fallo hardware", "Error software", "Caída red", "Virus malware", "Phishing ataque", "Acceso no autorizado", "Denegación servicio", "Sabotaje físico", "Impresora atascada", "Computadora lenta", "otros" }));

        Marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Marca.setForeground(new java.awt.Color(51, 255, 204));
        Marca.setText("Marca:");

        txtDispositivoAfectado.setBackground(new java.awt.Color(204, 255, 255));

        DispositivoAfectado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DispositivoAfectado.setForeground(new java.awt.Color(51, 255, 204));
        DispositivoAfectado.setText("Dispositivo Afectado:");

        txtMarca.setBackground(new java.awt.Color(204, 255, 255));
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        NumeroDeSerie.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NumeroDeSerie.setForeground(new java.awt.Color(51, 255, 204));
        NumeroDeSerie.setText("Numero De Serie:");

        txtModelo.setBackground(new java.awt.Color(204, 255, 255));
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        Modelo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Modelo.setForeground(new java.awt.Color(51, 255, 204));
        Modelo.setText("Modelo:");

        txtNumeroDeSerie.setBackground(new java.awt.Color(204, 255, 255));
        txtNumeroDeSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeSerieActionPerformed(evt);
            }
        });

        Ubicacion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Ubicacion.setForeground(new java.awt.Color(51, 255, 204));
        Ubicacion.setText("Ubicación:");

        txtUbicacion.setBackground(new java.awt.Color(204, 255, 255));

        Descripción.setBackground(new java.awt.Color(51, 255, 204));
        Descripción.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descripción.setForeground(new java.awt.Color(51, 255, 204));
        Descripción.setText("Descripción:");

        txtDescripcion.setBackground(new java.awt.Color(204, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        btnInicio.setBackground(new java.awt.Color(0, 0, 204));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ir a al inicio");
        btnInicio.setAutoscrolls(true);
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnGuardaryenviar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardaryenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardaryenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardaryenviar.setText("Guardar y enviar");

        btnRegresar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(51, 255, 204));
        Hora.setText("Hora:");

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 255, 204));
        Fecha.setText("Fecha:");

        javax.swing.GroupLayout TecnicoLayout = new javax.swing.GroupLayout(Tecnico);
        Tecnico.setLayout(TecnicoLayout);
        TecnicoLayout.setHorizontalGroup(
            TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(TecnicoLayout.createSequentialGroup()
                        .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(TecnicoLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Incidente))
                            .addGroup(TecnicoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DispositivoAfectado)
                                    .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Marca)
                                        .addComponent(Modelo)
                                        .addComponent(NumeroDeSerie)
                                        .addComponent(Ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                        .addComponent(txtNumeroDeSerie)
                                        .addComponent(txtModelo)
                                        .addComponent(txtMarca)
                                        .addComponent(txtDispositivoAfectado))
                                    .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Descripción, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Hora)
                            .addComponent(Fecha)
                            .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(TecnicoLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInicio)
                        .addGap(59, 59, 59))))
            .addGroup(TecnicoLayout.createSequentialGroup()
                .addGap(344, 344, 344)
                .addComponent(btnGuardaryenviar)
                .addGap(0, 356, Short.MAX_VALUE))
        );
        TecnicoLayout.setVerticalGroup(
            TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TecnicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Incidente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DispositivoAfectado)
                    .addComponent(Hora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDispositivoAfectado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marca)
                    .addComponent(Fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Modelo)
                    .addComponent(Descripción, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TecnicoLayout.createSequentialGroup()
                        .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(NumeroDeSerie)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumeroDeSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ubicacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(btnGuardaryenviar)
                .addGap(18, 18, 18)
                .addGroup(TecnicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnInicio))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tecnico, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtNumeroDeSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeSerieActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
 /*       VistaLogin p3= new VistaLogin ();
        p3.setSize(830, 530);
        p3.setLocation(0,0);
        Tecnico.removeAll();
        Tecnico.add(p3);
        Tecnico.revalidate();
        Tecnico.repaint();*/
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
       /* ReporteIncidentePanel p4= new ReporteIncidentePanel();
        p4.setSize(830, 530);
        p4.setLocation(0,0);
        Tecnico.removeAll();
        Tecnico.add(p4);
        Tecnico.revalidate();
        Tecnico.repaint(); */  
    }//GEN-LAST:event_btnRegresarActionPerformed

    public void resetCampos() {
        
        this.SelectorIncidente.setSelectedIndex(0);
        this.txtDispositivoAfectado.setText("");
        this.txtMarca.setText("");
        this.txtModelo.setText("");
       
        this.txtNumeroDeSerie.setText("");
        this.txtUbicacion.setText("");
       
        this.txtDescripcion.setText("");
    }
    
    
    
    public List<String> verificarCampos() {
    
        List<String> errores = new ArrayList<>();

    if (txtDescripcion.getText().isBlank()) {
        errores.add("La descripción no puede estar vacía.");
    }
    
    if(txtDescripcion.getText().length() > 250) {
        errores.add("La descripcion no puede exceder los 250 caracteres");
    }
    
    
    
    if (txtDispositivoAfectado.getText().isBlank()) {
        errores.add("El dispositivo afectado no puede estar vacío.");
    }
    
    if (txtDispositivoAfectado.getText().length() > 25) {
        errores.add("El dispositivo afectado no puede exceder los 25 caracteres");
    }
    
   
    if (txtMarca.getText().isBlank()) {
        errores.add("La marca no puede estar vacía.");
    } else {
        
        if (txtMarca.getText().length() > 25) {
            errores.add("La marca no debe acceder los 25 caracteres");
        }
    
        if (!ValidadorCamposIncidente.validarMarca(txtMarca.getText())) {
            errores.add("Marca deben ser solo letras");
        }
        
    }

    if (txtUbicacion.getText().isBlank()) {
        errores.add("La ubicacion no puede estar vacia");
    } else {
        if (!ValidadorCamposIncidente.validarUbicacion(txtUbicacion.getText())) {
            errores.add("La ubicacion debe tener el formato: \"AULA-302B\" ");
        }
        if (txtUbicacion.getText().length() > 25 ) {
            errores.add("La ubicacion no puede exceder los 25 caracteres");
        }
    }
  
    if (txtModelo.getText().isBlank()) {
        errores.add("El modelo no puede estar vacío.");
    }
    
    if (txtModelo.getText().length() > 25 ) {
        errores.add("El modelo no puede exceder los 25 caracteres");
    }
    
    
    if (txtNumeroDeSerie.getText().isBlank()) {
        errores.add("El número de serie no puede estar vacío.");
    }
    
      if (txtNumeroDeSerie.getText().length() > 25 ) {
        errores.add("El numero de serie no puede exceder los 25 caracteres");
    }
    

    this.errores = errores;
    
    return errores;
        
        
            
    }
    
    public HashMap<String, Object> getCamposIncidenteTecnico() {
        HashMap<String, Object> campos = new HashMap<>();
        
        campos.put("titulo", this.SelectorIncidente.getSelectedItem().toString());
        campos.put("descripcion", this.txtDescripcion.getText());
        campos.put("dispositivo", this.txtDispositivoAfectado.getText());
        campos.put("marca", this.txtMarca.getText());
        campos.put("modelo", this.txtModelo.getText());
        campos.put("serie", this.txtNumeroDeSerie.getText());
        campos.put("fecha", this.spinnerFecha.getValue());
        campos.put("hora", this.spinnerHora.getValue());
        campos.put("ubicacion", txtUbicacion.getText());
        
        return campos;
    }
    
    
     public void mostrarError() {
        String errs = String.join("\n", this.errores);
        JOptionPane.showMessageDialog(
            this,                
             errs,             
            "Error al Enviar",    
            JOptionPane.ERROR_MESSAGE 
        );
    }
     
    public void mostrarErrorBaseDeDatos() {
        JOptionPane.showMessageDialog(
            this,                
             "error de conexion",             
            "Error al Enviar",    
            JOptionPane.ERROR_MESSAGE 
        );
    }

    
    public void mostrarExito(String mensaje) {
        JOptionPane.showMessageDialog(
            this,
            mensaje,
            "Envío Exitoso",
            JOptionPane.INFORMATION_MESSAGE
        );
    }
    
    
    
    
    public void addbtnRegresar(ActionListener listener){
            btnRegresar.addActionListener(listener);
    }
    public void addbtnInicio(ActionListener listener){
            btnInicio.addActionListener(listener);
    }
    
    public void addBotonEnviarListener(ActionListener listener) {
        btnGuardaryenviar.addActionListener(listener);
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripción;
    private javax.swing.JLabel DispositivoAfectado;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Incidente;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JLabel NumeroDeSerie;
    private javax.swing.JComboBox<String> SelectorIncidente;
    private javax.swing.JPanel Tecnico;
    private javax.swing.JLabel Ubicacion;
    private javax.swing.JButton btnGuardaryenviar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JSpinner spinnerHora;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtDispositivoAfectado;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumeroDeSerie;
    private javax.swing.JTextField txtUbicacion;
    // End of variables declaration//GEN-END:variables
}
