/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import clases.IncidenteTecnico;
import java.awt.event.ActionListener;
import panels.IncidenteInstalacionesContainer;
import panels.IncidenteSeguridadContainer;
import panels.IncidenteTecnicoContainer;

/**
 *
 * @author alexis
 */
public class VistaDetalleIncidente extends javax.swing.JPanel {

    /**
     * Creates new form VistaDetalleIncidente
     */
    public VistaDetalleIncidente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiquetaId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        etiquetaTipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoDescripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        etiquetaEstado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        etiquetaPrioridad = new javax.swing.JLabel();
        etiquetaFecha = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        etiquetaAsignadoA = new javax.swing.JLabel();
        etiquetaCorreo = new javax.swing.JLabel();
        contedorTipoIncidente = new javax.swing.JPanel();
        botonVolver = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("ID: ");

        etiquetaId.setText("123");

        jLabel3.setText("Tipo: ");

        etiquetaTipo.setText("Tecnico");

        jLabel5.setText("Descripcion: ");

        textoDescripcion.setEditable(false);
        textoDescripcion.setColumns(20);
        textoDescripcion.setLineWrap(true);
        textoDescripcion.setRows(5);
        textoDescripcion.setWrapStyleWord(true);
        textoDescripcion.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(textoDescripcion);

        jLabel6.setText("Estado: ");

        etiquetaEstado.setText("Abierto");

        jLabel8.setText("Prioridad: ");

        jLabel9.setText("Fecha: ");

        etiquetaPrioridad.setText("Baja");

        etiquetaFecha.setText("25/06/2025");

        jLabel12.setText("Asignado a: ");

        etiquetaAsignadoA.setBackground(new java.awt.Color(255, 255, 255));
        etiquetaAsignadoA.setText("Sin asignar");
        etiquetaAsignadoA.setOpaque(true);

        etiquetaCorreo.setText("soporte@lol.com");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiquetaAsignadoA)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaTipo)
                                    .addComponent(etiquetaId)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaFecha)
                                    .addComponent(etiquetaPrioridad)
                                    .addComponent(etiquetaEstado)))
                            .addComponent(jLabel12)
                            .addComponent(etiquetaCorreo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiquetaId))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etiquetaTipo))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(etiquetaEstado))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(etiquetaPrioridad))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(etiquetaFecha))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAsignadoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaCorreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        contedorTipoIncidente.setBackground(new java.awt.Color(153, 255, 204));
        contedorTipoIncidente.setLayout(new java.awt.BorderLayout());

        botonVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contedorTipoIncidente, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonVolver)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contedorTipoIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    
    public void setEtiquetaId(String id) {
        this.etiquetaId.setText(id);
    }
    
    public void setEtiquetaTipo(String tipo) {
        this.etiquetaTipo.setText(tipo);
                
    }
    
    public void setEtiquetaEstado(String estado) {
        this.etiquetaTipo.setText(estado);
    }
    
    public void setEtiquetaPrioridad(String prioridad) {
        this.etiquetaPrioridad.setText(prioridad);
    }
    
    public void setEtiquetaAsignadoA(String asignadoA) {
        this.etiquetaAsignadoA.setText(asignadoA);
    }
    
    public void setEtiquetaFecha(String fecha) {
        this.etiquetaFecha.setText(fecha);
    }
    
    public void setTextDescripcion(String descripcion) {
        this.textoDescripcion.setText(descripcion);
    }
    
    public void setEtiquetaCorreo(String correo) {
        this.etiquetaCorreo.setText(correo);
    }
    
    public void setContenedorTipoSeguridad(String causa, String nivel, String tipo,
    String lugar) {
        
        IncidenteSeguridadContainer isc = new IncidenteSeguridadContainer(
                causa, nivel, tipo, lugar
        );
        
        this.contedorTipoIncidente.add(isc);
        
    } 
    
    public void setContenedorTipoTecnico(String dispositivo, String marca, String modelo, 
        String numeroSerie, String ubicacion) {
        
        
        
        IncidenteTecnicoContainer itc = new IncidenteTecnicoContainer(dispositivo, 
        marca, modelo, numeroSerie, ubicacion);
      
        this.contedorTipoIncidente.add(itc);
            
    }
    
    public void setContenedorTipoInstalaciones(String edificio, String numero, String piso,
            String tipoProblema) {
        
        IncidenteInstalacionesContainer iic = new IncidenteInstalacionesContainer(edificio,
                numero, piso, tipoProblema
        );
        
        this.contedorTipoIncidente.add(iic);
    }
    
    public void limpiarTipoDeIncidente() {
        this.contedorTipoIncidente.removeAll();
    }
    
    
    
    public void addVolverListener(ActionListener listener) {
        this.botonVolver.addActionListener(listener);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonVolver;
    private javax.swing.JPanel contedorTipoIncidente;
    private javax.swing.JLabel etiquetaAsignadoA;
    private javax.swing.JLabel etiquetaCorreo;
    private javax.swing.JLabel etiquetaEstado;
    private javax.swing.JLabel etiquetaFecha;
    private javax.swing.JLabel etiquetaId;
    private javax.swing.JLabel etiquetaPrioridad;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoDescripcion;
    // End of variables declaration//GEN-END:variables
}
