/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import utils.ValidadorCamposIncidente;

/**
 *
 * @author Alejo
 */
public class VistaIncidenteInstalacion extends javax.swing.JPanel {

    private SpinnerDateModel horaModel;
    private SpinnerDateModel fechaModel;
    private List<String> errores;

    /**
     * Creates new form IncidenteInstalacion
     */
    public VistaIncidenteInstalacion() {
        initComponents();
        
        horaModel = new SpinnerDateModel();
       spinnerHora.setModel(horaModel);

        fechaModel = new SpinnerDateModel();
       
        spinnerFecha.setModel(fechaModel);
        
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerHora, "HH:mm a");
        spinnerHora.setEditor(editor);
        
        JSpinner.DateEditor editorFecha = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(editorFecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel39 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Instalacion = new javax.swing.JPanel();
        SelectorIncidente = new javax.swing.JComboBox<>();
        Incidente = new javax.swing.JLabel();
        Edificio = new javax.swing.JLabel();
        txtEdificio = new javax.swing.JTextField();
        Piso = new javax.swing.JLabel();
        Numero = new javax.swing.JLabel();
        txtPiso = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        Hora = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        Descripcion = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        btnGuardaryenviar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        spinnerHora = new javax.swing.JSpinner();
        spinnerFecha = new javax.swing.JSpinner();

        jLabel39.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(51, 255, 204));
        jLabel39.setText("Hora:");

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(51, 255, 204));
        jLabel41.setText("Fecha:");

        Instalacion.setBackground(new java.awt.Color(0, 34, 64));
        Instalacion.setPreferredSize(new java.awt.Dimension(532, 452));

        SelectorIncidente.setBackground(new java.awt.Color(0, 0, 204));
        SelectorIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectorIncidente.setForeground(new java.awt.Color(255, 255, 255));
        SelectorIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corte energía", "Fuga agua", "Caída objetos", "Derrumbe estructura", "Cable expuesto", "Piso resbaladizo", "Puerta bloqueada", "Iluminación insuficiente", "Equipos dañados", "Señalización ausente", "otros" }));

        Incidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Incidente.setForeground(new java.awt.Color(51, 255, 204));
        Incidente.setText("Incidente:");

        Edificio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Edificio.setForeground(new java.awt.Color(51, 255, 204));
        Edificio.setText("Edificio:");

        txtEdificio.setBackground(new java.awt.Color(204, 255, 255));

        Piso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Piso.setForeground(new java.awt.Color(51, 255, 204));
        Piso.setText("Piso:");

        Numero.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Numero.setForeground(new java.awt.Color(51, 255, 204));
        Numero.setText("Número de oficina:");

        txtPiso.setBackground(new java.awt.Color(204, 255, 255));

        txtNumero.setBackground(new java.awt.Color(204, 255, 255));

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(51, 255, 204));
        Hora.setText("Hora:");

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 255, 204));
        Fecha.setText("Fecha:");

        Descripcion.setBackground(new java.awt.Color(51, 255, 204));
        Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(51, 255, 204));
        Descripcion.setText("Descripción:");

        txtDescripcion.setBackground(new java.awt.Color(204, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane5.setViewportView(txtDescripcion);

        btnRegresar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        btnGuardaryenviar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardaryenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardaryenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardaryenviar.setText("Guardar y enviar");

        btnInicio.setBackground(new java.awt.Color(0, 0, 204));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ir a al inicio");
        btnInicio.setAutoscrolls(true);

        javax.swing.GroupLayout InstalacionLayout = new javax.swing.GroupLayout(Instalacion);
        Instalacion.setLayout(InstalacionLayout);
        InstalacionLayout.setHorizontalGroup(
            InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio)
                .addGap(68, 68, 68))
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Incidente)
                    .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Edificio)
                    .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Piso)
                    .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Fecha)
                    .addComponent(Descripcion)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hora)
                    .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(349, 349, 349)
                .addComponent(btnGuardaryenviar)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        InstalacionLayout.setVerticalGroup(
            InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InstalacionLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hora)
                            .addComponent(Incidente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SelectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fecha)
                            .addComponent(Edificio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InstalacionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Piso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Numero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstalacionLayout.createSequentialGroup()
                        .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstalacionLayout.createSequentialGroup()
                        .addComponent(btnGuardaryenviar)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InstalacionLayout.createSequentialGroup()
                        .addGroup(InstalacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnInicio)
                            .addComponent(btnRegresar))
                        .addGap(45, 45, 45))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Instalacion, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Instalacion, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void addbtnRegresar(ActionListener listener){
        btnRegresar.addActionListener(listener);
    }
    public void addbtnInicio(ActionListener listener){
        btnInicio.addActionListener(listener);
    }
    
    public void addEnviarListener(ActionListener listener) {
        this.btnGuardaryenviar.addActionListener(listener);
    }
        
        public void resetCampos() {
            this.txtDescripcion.setText("");
            this.txtEdificio.setText("");
            this.txtNumero.setText("");
            this.txtPiso.setText("");
            
        }
        
        public boolean verificarCampos() {
    
            boolean error = false;
            this.errores = new ArrayList<>();
            
            List<String> errs = new ArrayList<>();
               
            if(this.txtDescripcion.getText().isBlank()){
                error = true;
                this.errores.add("La descripcion no puede estar vacia");
            } else {
                if(this.txtDescripcion.getText().length() > 250) {
                    this.errores.add("La descripcion no puede estar vacia");
                }
            }
            
            if (this.txtEdificio.getText().isBlank()) {
                error = true;
                this.errores.add("El edificio no puede esta vacio");
            } 
            
            if (this.txtNumero.getText().isBlank()) {
                error = true;
                this.errores.add("El numero de oficina no puede esta vacio");
            } else {
                error |= !ValidadorCamposIncidente.validarNumeroOficina(this.txtNumero.getText());
                if (error) {
                    this.errores.add("El numero de oficina debe ser desde 1 a 999");
                }
            }
            
            if (this.txtPiso.getText().isBlank()) {
                error = true;
                this.errores.add("El piso no puede esta vacio");
            } else {
                error |= !ValidadorCamposIncidente.validarPiso(this.txtPiso.getText());
                if(error) {
                    this.errores.add("El numero de piso debe ser desde 1 a 99");
                }
            }
            
           
    
            return error;
       
            
    }
        
        public HashMap<String, Object> getCamposIncidenteInstalacion() {
            
            HashMap<String, Object> campos = new HashMap<>();
            
            campos.put("descripcion", this.txtDescripcion.getText());
            campos.put("titulo", this.SelectorIncidente.getSelectedItem().toString());
            campos.put("edificio", this.txtEdificio.getText());
            campos.put("numero", this.txtNumero.getText());
            campos.put("piso", this.txtPiso.getText());
            campos.put("fecha", spinnerFecha.getValue());
            campos.put("hora", spinnerHora.getValue());
            
            return campos;
        }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Edificio;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Incidente;
    private javax.swing.JPanel Instalacion;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel Piso;
    private javax.swing.JComboBox<String> SelectorIncidente;
    private javax.swing.JButton btnGuardaryenviar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JSpinner spinnerHora;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtEdificio;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPiso;
    // End of variables declaration//GEN-END:variables

    public void mostrarErrorBaseDeDatos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void mostrarExito(String se_envio_el_incidente_correctamente) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void mostrarError() {
        String message = String.join("\n", this.errores);
        JOptionPane.showMessageDialog(this, message, "Error al enviar", JOptionPane.WARNING_MESSAGE);
    }
}
