/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;

/**
 *
 * @author alexis
 */
public class VistaInicioOperativo extends javax.swing.JPanel {

    /**
     * Creates new form VistaInicioOperativo
     */
    public VistaInicioOperativo() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        VistaInicio = new javax.swing.JPanel();
        etiquetaBienvenida = new javax.swing.JLabel();
        botonVerIncidentes = new javax.swing.JButton();
        BotonReportarIncidente = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        botonLogout = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel21.setText("jLabel9");

        jLabel24.setText("jLabel9");

        jLabel25.setText("jLabel9");

        setBackground(new java.awt.Color(0, 34, 64));

        VistaInicio.setBackground(new java.awt.Color(0, 34, 64));

        etiquetaBienvenida.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        etiquetaBienvenida.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaBienvenida.setText("Texto de bienvenida");

        botonVerIncidentes.setBackground(new java.awt.Color(255, 255, 204));
        botonVerIncidentes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonVerIncidentes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 4, true));
        botonVerIncidentes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonVerIncidentes.setLabel("Ver Incidente");
        botonVerIncidentes.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        BotonReportarIncidente.setBackground(new java.awt.Color(255, 255, 204));
        BotonReportarIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BotonReportarIncidente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 204), 4, true));
        BotonReportarIncidente.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        BotonReportarIncidente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BotonReportarIncidente.setLabel("Reportar Incidente");
        BotonReportarIncidente.setMargin(new java.awt.Insets(1, 14, 3, 14));
        BotonReportarIncidente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        BotonReportarIncidente.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        BotonReportarIncidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonReportarIncidenteActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        botonLogout.setBackground(new java.awt.Color(0, 0, 204));
        botonLogout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonLogout.setForeground(new java.awt.Color(255, 255, 255));
        botonLogout.setText("Salir");
        botonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLogoutActionPerformed(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setForeground(new java.awt.Color(102, 255, 255));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setForeground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout VistaInicioLayout = new javax.swing.GroupLayout(VistaInicio);
        VistaInicio.setLayout(VistaInicioLayout);
        VistaInicioLayout.setHorizontalGroup(
            VistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistaInicioLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonLogout)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistaInicioLayout.createSequentialGroup()
                .addContainerGap(95, Short.MAX_VALUE)
                .addComponent(botonVerIncidentes)
                .addGap(88, 88, 88)
                .addComponent(BotonReportarIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(VistaInicioLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(etiquetaBienvenida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        VistaInicioLayout.setVerticalGroup(
            VistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VistaInicioLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(etiquetaBienvenida)
                .addGap(52, 52, 52)
                .addGroup(VistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonReportarIncidente)
                    .addComponent(botonVerIncidentes))
                .addGap(33, 175, Short.MAX_VALUE)
                .addGroup(VistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistaInicioLayout.createSequentialGroup()
                        .addGroup(VistaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VistaInicioLayout.createSequentialGroup()
                        .addComponent(botonLogout)
                        .addGap(31, 31, 31))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(VistaInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VistaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BotonReportarIncidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonReportarIncidenteActionPerformed
       /* ReporteIncidentePanel p3 = new ReporteIncidentePanel();
                p3.setSize(830, 530);
        p3.setLocation(0,0);
        VistaInicio.removeAll();
        VistaInicio.add(p3);
        VistaInicio.revalidate();
        VistaInicio.repaint(); */
    }//GEN-LAST:event_BotonReportarIncidenteActionPerformed

    private void botonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonLogoutActionPerformed

    public void setSaludo(String nombre) {
        etiquetaBienvenida.setText("¡Bienvenido, " + nombre + "!");
    }

    public void addLogoutListener(ActionListener listener) {
        botonLogout.addActionListener(listener);
    }
    
    public void addVerIncidentesListener (ActionListener listener) {
        botonVerIncidentes.addActionListener(listener);
    }
    public void addReportarIncidenteListener(ActionListener listener){
        BotonReportarIncidente.addActionListener(listener);
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonReportarIncidente;
    private javax.swing.JPanel VistaInicio;
    private javax.swing.JButton botonLogout;
    private javax.swing.JButton botonVerIncidentes;
    private javax.swing.JLabel etiquetaBienvenida;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    // End of variables declaration//GEN-END:variables
}
