/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;

/**
 *
 * @author Alejo
 */
public class VistaIncidenteSeguridad extends javax.swing.JPanel {

    private SpinnerDateModel horaModel;
    private SpinnerDateModel fechaModel;
    private List<String> errores;

    /**
     * Creates new form IncidenteSeguridad
     */
    public VistaIncidenteSeguridad() {
        initComponents();
        
        horaModel = new SpinnerDateModel();
       spinnerHora.setModel(horaModel);

        fechaModel = new SpinnerDateModel();
       
        spinnerFecha.setModel(fechaModel);
        
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinnerHora, "HH:mm a");
        spinnerHora.setEditor(editor);
        
        JSpinner.DateEditor editorFecha = new JSpinner.DateEditor(spinnerFecha, "dd/MM/yyyy");
        spinnerFecha.setEditor(editorFecha);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        nivelGrupo = new javax.swing.ButtonGroup();
        Seguridad = new javax.swing.JPanel();
        selectorIncidente = new javax.swing.JComboBox<>();
        Incidente = new javax.swing.JLabel();
        Hora = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        NivelDeRiesgo = new javax.swing.JLabel();
        txtLugar = new javax.swing.JTextField();
        Lugar = new javax.swing.JLabel();
        nivelBajo = new javax.swing.JRadioButton();
        nivelMedio = new javax.swing.JRadioButton();
        nivelAlto = new javax.swing.JRadioButton();
        Descripcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();
        btnGuardaryenviar = new javax.swing.JButton();
        btnInicio = new javax.swing.JButton();
        spinnerHora = new javax.swing.JSpinner();
        spinnerFecha = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        txtCausa = new javax.swing.JTextField();

        jTextArea1.setBackground(new java.awt.Color(204, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        Seguridad.setBackground(new java.awt.Color(0, 34, 64));
        Seguridad.setPreferredSize(new java.awt.Dimension(532, 452));

        selectorIncidente.setBackground(new java.awt.Color(0, 0, 204));
        selectorIncidente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectorIncidente.setForeground(new java.awt.Color(255, 255, 255));
        selectorIncidente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Robo bienes", "Incendio instalaciones", "Vandalismo propiedad", "Intrusión no autorizada", "Sabotaje interno", "Sabotaje externo", "Inundación daños", "Terremoto estructural", "Corte energía", "Violencia laboral", "otros" }));

        Incidente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Incidente.setForeground(new java.awt.Color(51, 255, 204));
        Incidente.setText("Incidente:");

        Hora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hora.setForeground(new java.awt.Color(51, 255, 204));
        Hora.setText("Hora:");

        Fecha.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Fecha.setForeground(new java.awt.Color(51, 255, 204));
        Fecha.setText("Fecha:");

        NivelDeRiesgo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        NivelDeRiesgo.setForeground(new java.awt.Color(51, 255, 204));
        NivelDeRiesgo.setText("Nivel de impacto:");

        txtLugar.setBackground(new java.awt.Color(204, 255, 255));
        txtLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLugarActionPerformed(evt);
            }
        });

        Lugar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Lugar.setForeground(new java.awt.Color(51, 255, 204));
        Lugar.setText("Lugar:");

        nivelBajo.setBackground(new java.awt.Color(0, 51, 255));
        nivelGrupo.add(nivelBajo);
        nivelBajo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nivelBajo.setForeground(new java.awt.Color(255, 255, 255));
        nivelBajo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 102), new java.awt.Color(255, 255, 204), null, null));
        nivelBajo.setLabel("Bajo");

        nivelMedio.setBackground(new java.awt.Color(0, 51, 255));
        nivelGrupo.add(nivelMedio);
        nivelMedio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nivelMedio.setForeground(new java.awt.Color(255, 255, 255));
        nivelMedio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 102), new java.awt.Color(255, 255, 204), null, null));
        nivelMedio.setLabel("Medio");
        nivelMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelMedioActionPerformed(evt);
            }
        });

        nivelAlto.setBackground(new java.awt.Color(0, 51, 255));
        nivelGrupo.add(nivelAlto);
        nivelAlto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nivelAlto.setForeground(new java.awt.Color(255, 255, 255));
        nivelAlto.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(51, 255, 102), new java.awt.Color(255, 255, 204), null, null));
        nivelAlto.setLabel("Alto");

        Descripcion.setBackground(new java.awt.Color(51, 255, 204));
        Descripcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(51, 255, 204));
        Descripcion.setText("Descripción:");

        txtDescripcion.setBackground(new java.awt.Color(204, 255, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane2.setViewportView(txtDescripcion);

        btnRegresar.setBackground(new java.awt.Color(0, 0, 204));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        btnGuardaryenviar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardaryenviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardaryenviar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardaryenviar.setText("Guardar y enviar");

        btnInicio.setBackground(new java.awt.Color(0, 0, 204));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnInicio.setText("Ir a al inicio");
        btnInicio.setAutoscrolls(true);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Causa: ");

        txtCausa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCausaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SeguridadLayout = new javax.swing.GroupLayout(Seguridad);
        Seguridad.setLayout(SeguridadLayout);
        SeguridadLayout.setHorizontalGroup(
            SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnRegresar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInicio)
                .addGap(83, 83, 83))
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Incidente)
                    .addComponent(jLabel1)
                    .addComponent(Lugar)
                    .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NivelDeRiesgo)
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addComponent(nivelBajo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivelMedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nivelAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCausa, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(selectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Hora)
                    .addComponent(Fecha)
                    .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Descripcion)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGap(328, 328, 328)
                .addComponent(btnGuardaryenviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SeguridadLayout.setVerticalGroup(
            SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SeguridadLayout.createSequentialGroup()
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Incidente)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SeguridadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Hora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinnerHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectorIncidente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spinnerFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addComponent(txtCausa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SeguridadLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(SeguridadLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Lugar)))))
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NivelDeRiesgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nivelBajo)
                            .addComponent(nivelMedio)
                            .addComponent(nivelAlto)))
                    .addGroup(SeguridadLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnGuardaryenviar)
                .addGap(18, 18, 18)
                .addGroup(SeguridadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresar)
                    .addComponent(btnInicio))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Seguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLugarActionPerformed

    private void nivelMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelMedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelMedioActionPerformed

    private void txtCausaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCausaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCausaActionPerformed

    public void addbtnRegresar(ActionListener listener){
        btnRegresar.addActionListener(listener);
    }
    public void addbtnInicio(ActionListener listener){
        btnInicio.addActionListener(listener);
    } 
    
    public void addEnviar(ActionListener listener) {
        btnGuardaryenviar.addActionListener(listener);
    }
    
    public boolean verificarCampos() {
        boolean error = false;
        this.errores = new ArrayList<>();
        
        if(this.txtCausa.getText().isBlank()) {
            error = true;
            this.errores.add("La causa no puede estar vacia");
            
        } 
        if(this.txtDescripcion.getText().isBlank()) {
            error = true;
            this.errores.add("La descripcion no puede estar vacia");
        }
        
        if(this.txtLugar.getText().isBlank()) {
            error = true;
            this.errores.add("El lugar no puede estar vacio");
        }
        
        if (this.nivelGrupo.getSelection() == null) {
            error = true;
            this.errores.add("Selecione un nivel de impacto");
        }
        
        
        return error;
    }
    
    public HashMap<String, Object> getCampos() {
        HashMap<String, Object> campos = new HashMap<>();
        
        campos.put( "causa" ,this.txtCausa.getText());
        campos.put( "descripcion",this.txtDescripcion.getText());
        campos.put( "lugar" ,this.txtLugar.getText());
        campos.put( "tipoIncidente",this.selectorIncidente.getSelectedItem().toString());
        campos.put( "fecha" , this.spinnerFecha.getValue());
        campos.put("hora",  spinnerHora.getValue());
        
        Enumeration<AbstractButton> botones = this.nivelGrupo.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.isSelected()) {
                campos.put("nivelImpacto", boton.getText().toUpperCase());
                break;
            }
        } 
        return campos;
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Descripcion;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Incidente;
    private javax.swing.JLabel Lugar;
    private javax.swing.JLabel NivelDeRiesgo;
    private javax.swing.JPanel Seguridad;
    private javax.swing.JButton btnGuardaryenviar;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton nivelAlto;
    private javax.swing.JRadioButton nivelBajo;
    private javax.swing.ButtonGroup nivelGrupo;
    private javax.swing.JRadioButton nivelMedio;
    private javax.swing.JComboBox<String> selectorIncidente;
    private javax.swing.JSpinner spinnerFecha;
    private javax.swing.JSpinner spinnerHora;
    private javax.swing.JTextField txtCausa;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtLugar;
    // End of variables declaration//GEN-END:variables

    public void mostrarError() {
        String errores = String.join("\n", this.errores);
        JOptionPane.showMessageDialog(this, errores, "Error al enviar" , JOptionPane.ERROR_MESSAGE);
    }

    public void resetCampos() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public void mostrarExito() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        JOptionPane.showMessageDialog(this, "Se envio el incidente correctamente", "Exito", JOptionPane.INFORMATION_MESSAGE);
    }

    public void mostrarErrorBaseDeDatos() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
