/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

/**
 *
 * @author alexis
 */
public class IncidenteSeguridadContainer extends javax.swing.JPanel {

    /**
     * Creates new form IncidenteSeguridadContainer
     * @param causa
     * @param nivel
     * @param tipo
     * @param lugar
     */
    public IncidenteSeguridadContainer(String causa, String nivel, String tipo, String lugar ) {
        initComponents();
        
        this.etiqueCausa.setText(causa);
        this.etiquetaNivel.setText(nivel);
        this.etiquetaTipo.setText(tipo);
        this.etitquetaLugar.setText(lugar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiquetaTipo = new javax.swing.JLabel();
        etiquetaNivel = new javax.swing.JLabel();
        etiqueCausa = new javax.swing.JLabel();
        etitquetaLugar = new javax.swing.JLabel();

        jLabel2.setText("Tipo: ");

        jLabel3.setText("Nivel de Impacto: ");

        jLabel4.setText("Causa: ");

        jLabel5.setText("Lugar: ");

        etiquetaTipo.setText("tipo");

        etiquetaNivel.setText("nivel");

        etiqueCausa.setText("causa");

        etitquetaLugar.setText("lugar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTipo)
                    .addComponent(etiquetaNivel)
                    .addComponent(etiqueCausa)
                    .addComponent(etitquetaLugar))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiquetaTipo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etiquetaNivel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(etiqueCausa))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etitquetaLugar))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueCausa;
    private javax.swing.JLabel etiquetaNivel;
    private javax.swing.JLabel etiquetaTipo;
    private javax.swing.JLabel etitquetaLugar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
