/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

/**
 *
 * @author alexis
 */
public class IncidenteInstalacionesContainer extends javax.swing.JPanel {

    /**
     * Creates new form IncidenteInstalacionesContainer
     */
    public IncidenteInstalacionesContainer(String edificio, String numero, String piso, String tipoProblema) {
        initComponents();
        this.etiquetaEdificio.setText(edificio);
        this.etiquetaNumero.setText(numero);
        this.etiquetaPiso.setText(piso);
        this.etiquetaTipoProblema.setText(tipoProblema);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelPiso = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiquetaTipoProblema = new javax.swing.JLabel();
        etiquetaEdificio = new javax.swing.JLabel();
        etiquetaPiso = new javax.swing.JLabel();
        etiquetaNumero = new javax.swing.JLabel();

        jLabel2.setText("Edificio: ");

        jLabel3.setText("Tipo de problema: ");

        labelPiso.setText("Piso: ");

        jLabel5.setText("Numero de oficina:");

        etiquetaTipoProblema.setText("tipo");

        etiquetaEdificio.setText("edificio a");

        etiquetaPiso.setText("piso 12");

        etiquetaNumero.setText("123");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(labelPiso)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaTipoProblema)
                    .addComponent(etiquetaEdificio)
                    .addComponent(etiquetaPiso)
                    .addComponent(etiquetaNumero))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etiquetaTipoProblema))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(etiquetaEdificio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPiso)
                    .addComponent(etiquetaPiso))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(etiquetaNumero))
                .addContainerGap(148, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaEdificio;
    private javax.swing.JLabel etiquetaNumero;
    private javax.swing.JLabel etiquetaPiso;
    private javax.swing.JLabel etiquetaTipoProblema;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelPiso;
    // End of variables declaration//GEN-END:variables
}
