/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panels;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author alexis
 */
public class IncidenteTile extends javax.swing.JPanel {

    private String idIncidente;
    private final Color colorOriginal = this.getBackground();
    /**
     * Creates new form IncidenteTile
     * @param id
     * @param tipo
     * @param fecha
     * @param estado
     * @param reportadoPor
     * @param asignadoA
     * @param prioridad
     */
    public IncidenteTile(String id, String tipo, String fecha, String estado, String asignadoA, String prioridad) {
        initComponents();
        
        this.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        
        this.idIncidente = id;
        
        etiquetaId.setText(id);
        etiquetaTipo.setText(tipo);
        etiquetaFecha.setText(fecha);
        etiquetaEstado.setText(estado);
        etiquetaAsignadoA.setText("SIN ASIGNAR");
        
        if (asignadoA != null) {
            etiquetaAsignadoA.setText(asignadoA);
        }
        
        etiquetaPrioridad.setText(prioridad);
        
        
       
        addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                
                firePropertyChange("incidenteClicked", null, idIncidente);
                
            }
            
            @Override
            public void mouseEntered(MouseEvent e) {
                // El ratón ha entrado en el área del botón
                
                setBackground(Color.CYAN); // Cambia el color de fondo
            }

            @Override
            public void mouseExited(MouseEvent e) {
                // El ratón ha salido del área del botón
                setBackground(colorOriginal); // Vuelve al color original
            }
        
        });
    }
    
    public IncidenteTile() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaId = new javax.swing.JLabel();
        etiquetaTipo = new javax.swing.JLabel();
        etiquetaFecha = new javax.swing.JLabel();
        etiquetaEstado = new javax.swing.JLabel();
        etiquetaAsignadoA = new javax.swing.JLabel();
        etiquetaPrioridad = new javax.swing.JLabel();

        etiquetaId.setText("123");

        etiquetaTipo.setText("Tecnico");

        etiquetaFecha.setText("16-06-2025");

        etiquetaEstado.setText("abierto");

        etiquetaAsignadoA.setText("asignado a");

        etiquetaPrioridad.setText("baja");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etiquetaId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaAsignadoA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaPrioridad)
                .addGap(0, 343, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(etiquetaId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(etiquetaFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(etiquetaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(etiquetaAsignadoA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(etiquetaPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiquetaAsignadoA;
    private javax.swing.JLabel etiquetaEstado;
    private javax.swing.JLabel etiquetaFecha;
    private javax.swing.JLabel etiquetaId;
    private javax.swing.JLabel etiquetaPrioridad;
    private javax.swing.JLabel etiquetaTipo;
    // End of variables declaration//GEN-END:variables
}
